In [1]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())

2.11.0+cu128
True


In [2]:
import torch

x = torch.tensor([1, 2, 3])
print(x)

tensor([1, 2, 3])


In [3]:
a = torch.tensor([2, 4, 6])
b = torch.tensor([1, 2, 3])

print("Addition:", a + b)
print("Multiplication:", a * b)

Addition: tensor([3, 6, 9])
Multiplication: tensor([ 2,  8, 18])


In [4]:
device = "cuda"

x = torch.tensor([10, 20, 30]).to(device)

print(x)
print("Device:", x.device)

tensor([10, 20, 30], device='cuda:0')
Device: cuda:0


In [5]:
import torch

x = torch.tensor(2.0, requires_grad=True)

y = x**2

y.backward()

print(x.grad)

tensor(4.)


In [6]:
x = torch.tensor(3.0, requires_grad=True)

y = x**3 + 2*x

y.backward()

print(x.grad)

tensor(29.)


In [7]:
import torch

# fake data
x = torch.randn(100, 1)
y = 2*x + 1 + torch.randn(100, 1) * 0.1

In [8]:
import torch

# initialize parameters randomly
w = torch.randn(1, requires_grad=True)
b = torch.randn(1, requires_grad=True)

print("Initial weight:", w)
print("Initial bias:", b)

Initial weight: tensor([0.5057], requires_grad=True)
Initial bias: tensor([0.1610], requires_grad=True)


In [9]:
learning_rate = 0.01

for epoch in range(100):

    # prediction
    y_pred = w*x + b

    # loss (error)
    loss = ((y_pred - y)**2).mean()

    # backward (calculate gradients)
    loss.backward()

    # update weights
    with torch.no_grad():
        w -= learning_rate * w.grad
        b -= learning_rate * b.grad

        # reset gradients
        w.grad.zero_()
        b.grad.zero_()

    if epoch % 10 == 0:
        print(f"Epoch {epoch}, Loss: {loss.item()}")

Epoch 0, Loss: 2.808586359024048
Epoch 10, Loss: 1.9034756422042847
Epoch 20, Loss: 1.2920820713043213
Epoch 30, Loss: 0.8787611126899719
Epoch 40, Loss: 0.5991166830062866
Epoch 50, Loss: 0.4097582697868347
Epoch 60, Loss: 0.28142863512039185
Epoch 70, Loss: 0.19438453018665314
Epoch 80, Loss: 0.13529299199581146
Epoch 90, Loss: 0.09514276683330536


In [10]:
print("Final weight (w):", w.item())
print("Final bias (b):", b.item())

Final weight (w): 1.7564599514007568
Final bias (b): 0.9122634530067444


In [11]:
x_test = torch.tensor([[1.0], [2.0], [3.0]])

y_pred = w*x_test + b

print("Predictions:")
print(y_pred)

Predictions:
tensor([[2.6687],
        [4.4252],
        [6.1816]], grad_fn=<AddBackward0>)
